### ISSUE TITLE
single argument as undefined

### ISSUE THREAD

**Issue by Mattchewone** [canjs/can-observable-array#30]
When creating a `DefineArray` with a single argument I am seeing the value as `undefined`

Example:
```js
import { DefineArray } from "//unpkg.com/can@5/everything.mjs";

const strings1 = new DefineArray(...[1]); // -> [undefined]
const strings2 = new DefineArray(...[1, 2]); // -> [1, 2]
```

Codepen - https://codepen.io/mattchewone-the-looper/pen/KjJZmd?editors=0011

**Comment by phillipskevin** [comment]
@Mattchewone can this be closed? You confirmed this is working the same as `new Array(5)`, right?

**Comment by Mattchewone** [comment]
Yup
