### ISSUE TITLE
Proposal: new ObservableArray( array | number )

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-observable-array#41]
__tldr__ Make `new ObservableArray()` take an array of items instead of behaving like the `Array` constructor.

Related:
 - #30 

## Proposal 

The `Array` constructor works as follows:

- `new Array(...values)` - Takes arguments and converts them to items in the array: 
   ```js
   new Array(1,2,3) //-> [1,2,3]
   ```
- `new Array(number)` - Creates an array of the number length.
   ```js
   new Array(1) //-> [undefined]
   ```

I suggest changing `ObservableArray` to work as follows:

- `new ObservableArray(array)` - Convert the `array` to an observable array of values
   ```js
   new ObservableArray([1,2,3]) //-> ObservableArray[1,2,3]
   ```
- `new ObservableArray(number)` - Creates an observable array of the number length.
   ```js
   new ObservableArray(1) //-> ObservableArray[undefined]
   ```

Specifically, I propose that `ObservableArray()` should take an array of items as its first argument (`new ObservableArray([1,2,3])`) instead of using the arguments as the items (`new ObservableArray(1,2,3)`.

Rationale:

- ObservableArrays can be initialized to a single number value
- `new Array()`'s API violates expectations (argument type AND arguments length matters)
- Following `new Array()` API would make performance worse for the most common use cases of `new ObservableArray()`
- We could support initializing an array with items and properties `new ObservableArray([],{})`

## ObservableArrays can be initialized to a single number value

Currently, it is impossible to initialize `ObservableArray`s to a single number value.

For example:

```
new ObservableArray(2) //-> ObservableArray[undefined, undefined]
```

Instead, one must do it like:

```js
var numbers = new ObservableArray();
numbers.push(2);
```

The above code causes mutations. 
- We generally warn about creating mutations in getters. 
- Initialization avoids dispatching events.  This would try to dispatch events and be slower for it.

## `new Array()`'s API violates expectations

While changing ObservableArray to __not__ match Array would likely violate expectations, `Array`'s API almost certainly violates people's expectations already.  For example #30.

This is because `Array` changes its behavior based on argument type _AND_ the number of arguments.  This can create confusing situations.

For example, say users were getting an array of strings.  For performance reasons, they would likely do:

```js
var strings = GET_STRINGS();

var observableStrings = new ObservableArray(...strings );
```  

However, if this situation were changed to an array of numbers, they would not be able to do this if `GET_NUMBERS()` could ever return an array of a single number.  For optimal performance, they would have to do:

```js
var numbers = GET_NUMBERS();

if(numbers.length === 1 ){
  var observableNumers = new ObservableNumbers();
  observableNumbers.push(numbers[0])
} else {
  var observableNumbers = new ObservableArray(...numbers );
}
```  

It feels very strange to me to use the same pattern _everywhere_ except for a particular type. Especially when converting an array of items into an observable array is the most common use case of `new ObservableArray()`.

## Performance 

Using the spread operator `...` creates an additional `O(n)` performance and memory cost.  

Consider the following examples:

__Way 1__ - Passes an array:

```js
var items = [1,2,3,4, ...., 10000];
function loop(items) {
  for(var i  = 0 ; i < items.length; i++ ){
   items[i]
 }
}
loop( items )
```

__Way 2__ - Spread in an array

```js
var items = [1,2,3,4, ...., 10000];
function loop() {
  for(var i  = 0 ; i < arguments.length; i++ ){
   arguments[i]
 }
}
loop(...items )
```

__Way 1__ Should be faster because __Way 2__ needs to create the `arguments` structure.  THis involves copying the `items` array.  

As mentioned previously, creating observable arrays from normal arrays is the most common use case of `new ObservableArray()`.  Consider a model getting 1000s of records and converting them to an ObservableArray of model instances.  This would create an additional `O(n)` operation.

## `new ObservableArray([],{})`

Service data can often come back like:

```
{
  data: [{id: 1},{id: 2}],
  count: 1000
}
```

Currently, we take the non-data properties and add them to an array as "expando" properties.  These expando properties cause events and are slow.  We could enable creating both items and properties in initialization:

```js
new ObservableArray([{id: 1},{id: 2}], {count: 1000})
```

## (my) Conclusions

While we _should_ copy the behavior of JavaScript's builtins by default.  I think this is a case where it's worth not following their patterns.  JavaScript array's have the benefit of creating single-number arrays with _Array Literals_ like `[2]`.  And `new Array( array )` doesn't really make much sense ... as `array` would already be an `array`.

Given the reasons above, I think it's in our best interest to change `new ObseravbleArray()`.  There might be confusion, but we can warn about it.  And the solutions rules are very easy understand.

## More research?

- What do other frameworks or libraries that make custom Array types do?

**Comment by Mattchewone** [comment]
I think that using 
```js
const items = new ObservableArray([1, 2, 3])
```
has the same implementation as `DefineList` in that respect and I quite like that pattern from a user perspective.

**Comment by phillipskevin** [comment]
We need to update the docs to reflect this change.

**Comment by phillipskevin** [comment]
Docs were updated in https://github.com/canjs/can-observable-array/pull/49.
