### ISSUE TITLE
Add / Remove events not being fired

### ISSUE THREAD

**Issue by MarceloFonseca** [canjs/can-observable-array#76]
According to [this example](https://codepen.io/MarceloFonseca/pen/yLNyYgP) taken from [CanJS Documentation](https://canjs.com/doc/can-observable-array.html) (Bottom of the page):

- `add` and `remove` events are not being fired, only the `length` one

I believe we should have this output:

`// remove ["eve"] 2`
`// length 2 3`
`// add ["Xerxes"] 1`
`// length 3 2`

And not only:

`// length 2 3`
`// length 3 2`

FYI: This was already raised and discussed in [Slack](https://bitovi-community.slack.com/archives/CFC22NZ8A/p1581089933031900?thread_ts=1581001481.029600&cid=CFC22NZ8A) :wink:

**Comment by cherifGsoul** [comment]
The slack discussion:
```
Marcelo Fonseca 
Hi @Cherif
As a context, I need to integrate a new ObservableArray in a big legacy DefineMap that supports a component (so no option to use an ObservableObject)
But bindings and response to events do not seem to work - I had the impression that they could be retro-fitted.
In this official CanJS example, are add and remove events expected to fire?
:arrow_right: https://codepen.io/MarceloFonseca/pen/yLNyYgP?editable=true&editors=0011
...because only length seems to be triggered.
Doc here:  https://canjs.com/doc/can-observable-array.html (Bottom of the page)
```

**Comment by MarceloFonseca** [comment]
Thank you @cherifGsoul, the original conversation is also linked in the original post. 

After some debugging I can see that, after removing an item (`.pop()` for instance) the process goes all the way until: `helpers.js:86`, at this point:

`(...)`
`else if (how === 'remove') {`
`         if (itemsDefinition && typeof itemsDefinition.removed === 'function') {`
`	         ObservationRecorder.ignore(itemsDefinition.removed).call(this, oldVal, index);`
`	}`
`}`
`(...)`

But `itemsDefinition` obtained originally from `var itemsDefinition = this._define.definitions["#"];` is an empty object, so theres no call to dispatch the event, apparently.
